# Generated by Django 2.0.4 on 2018-05-07 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='author',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='book',
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
