# Generated by Django 2.0.4 on 2018-05-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20180507_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='book_num',
            field=models.IntegerField(blank=True, verbose_name='小说数量'),
        ),
        migrations.AlterField(
            model_name='author',
            name='valuation',
            field=models.CharField(blank=True, max_length=400, verbose_name='评价'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_url',
            field=models.URLField(blank=True, max_length=100, verbose_name='链接'),
        ),
    ]
