# Generated by Django 2.0.4 on 2018-05-13 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20180507_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-book_lever',), 'verbose_name': '书籍', 'verbose_name_plural': '书籍'},
        ),
        migrations.AlterField(
            model_name='book',
            name='book_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_lever',
            field=models.FloatField(default=0, help_text='最大值为10', verbose_name='等级'),
        ),
    ]
