# Generated by Django 2.0.4 on 2018-05-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20180513_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='sex',
            field=models.BooleanField(choices=[(0, '男'), (1, '女')], default=0, max_length=1),
        ),
    ]
